version: "1"
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "admin"
    volumes:
        - postgres-db:/var/lib/postgresql/data
        - ./database_setup/db_setup.sql:/docker-entrypoint-initdb.d/1.sql

    ports:
      - "54320:5432"
volumes:
    postgres-db: